# Generated by Django 6.0 on 2025-12-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
