# Generated by Django 6.0 on 2025-12-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_appointment_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='informationpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
